repos:
  - repo: local
    hooks:
      - id: format
        name: format
        entry: hatch fmt
        language: python
        types: [python]
        pass_filenames: false
      - id: type-check
        name: type-check
        entry: hatch run types:check
        language: python
        types: [python]
        pass_filenames: false

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=700000"]
      - id: check-toml
      - id: check-yaml
